language: java
jdk:
- oraclejdk8
script:
- mvn clean deploy --settings settings.xml
after_success:
- mvn clean test jacoco:report coveralls:report
env:
  global:
  - secure: BKzUtLBlkXZDrra8RtV9T32734ol7E+url1g7YfYa+RAUETxZjV8pFKPhG22Xcm2GAH9ehm9GnVwf59qfPPwun2lu28Wpoo9epMk59GzIahKv5wtagRMOv185GKOQrsIhRz490heV3/2E/XIVyKuofdy3YJkUpNRBvTmB65Q/hI=
  - secure: YV/MTW0JV6W7oRM1oV8RSMhew7hEPxSCjxUbCkCXWkToBWJR4hkRCzyNKnH6V6ExcAEu7vMdt3FEPv4fAVqa0tCD9VpF1/RfjaN/QksZteC08D3gcWOC9mDJc0FFdnd9hhzedTInmoRzTHVzEad+aqqd4OrsN9lMoRhHq+OUoNM=
